### PR TITLE
Fix Datalab init action for Dataproc 1.0-1.3

### LINKED ISSUE #520: Pull Request #514 breaks initialisation (No such file error)
A recent pull request #514 
causes below error, which breaks initialisation

``` bash
+ touch /etc/hadoop /etc/hive /etc/spark /usr/lib/hadoop/lib/gcs-connector-1.6.10-hadoop2.jar /usr/lib/hadoop/lib/gcs-connector.jar /usr/lib/hadoop/lib/bigquery-connector-0.10.11-hadoop2.jar /usr/lib/hadoop/lib/bigquery-connector.jar '/usr/local/share/google/dataproc/lib/gcs*'
touch: cannot touch '/usr/local/share/google/dataproc/lib/gcs*': No such file or directory

```

### PR DESCRIPTION
**Pull request by medb**
Fixes #514 #520

### CODE REVIEW

File: datalab/datalab.sh [hunk 1]
```diff
@@ -40,9 +40,15 @@ CONNECTORS_LIB=/usr/lib/hadoop/lib
...
-if compgen -G "${CONNECTORS_LIB}/bigquery*" > /dev/null; then
-  VOLUMES+=$(echo " ${CONNECTORS_LIB}/bigquery*")
+if [[ -L ${CONNECTORS_LIB}/gcs-connector.jar ]]; then
+  VOLUMES+=" ${CONNECTORS_LIB}/gcs-connector.jar"
+else
+  VOLUMES+=" $(compgen -G ${CONNECTORS_LIB}/gcs*)"
+fi
+if [[ -L ${CONNECTORS_LIB}/bigquery-connector.jar ]]; then
+  VOLUMES+=" ${CONNECTORS_LIB}/bigquery-connector.jar"
+elif compgen -G "${CONNECTORS_LIB}/bigquery*" > /dev/null; then
```
Comment (functicons) [inline datalab/datalab.sh]: Is this condition necessary?

Comment (medb) [reply datalab/datalab.sh]: No, it will return empty string if BQ connector not available. Removed it.

Comment (medb) [reply datalab/datalab.sh]: Rolled back, if there no match `compgen` returns `1` exit code and fails init action execution.
