### PR TITLE
Leave hive on spark unchanged when using hive on tez (fixes #140)

### LINKED ISSUE #140: Tez init action breaks Spark
Hive on Tez requires Tez jars to be on the classpath. The Tez init action does correctly configure the classpath for hive, so running hive queries works.

However, Spark depends on Hive, so Tez jars also need to be on Spark's classpath. Here's a snippet of the error I saw when opening a spark shell:

```
$ spark-shell
java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':
  at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1053)
  at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:130)
  at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:130)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:129)
  at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:126)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:938)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$getOrCreate$5.apply(SparkSession.scala:938)
  at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
  at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
  at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
  at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
  at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
  at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:938)
  at org.apache.spark.repl.Main$.createSparkSession(Main.scala:97)
  ... 47 elided

...

Caused by: java.lang.reflect.InvocationTargetException: java.lang.NoClassDefFoundError: org/apache/tez/dag/api/SessionNotRunning
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:264)
  ... 78 more

...
```

Environment: Dataproc 1.2.5, single node n1-standard-4.

### PR DESCRIPTION
**Pull request by karth295**

### CODE REVIEW

**Comment by karth295** [comment]
Tested by creating hive table in `spark-shell`:

```
scala> spark.sql("create table foo (num int)")
res0: org.apache.spark.sql.DataFrame = []
```

And checking that it exists when using the `hive` CLI:

```
hive> show tables;
OK
foo
Time taken: 1.486 seconds, Fetched: 1 row(s)
```

File: tez/tez.sh [hunk 1]
```diff
@@ -24,6 +24,12 @@ hadoop_conf_dir="/etc/hadoop/conf"
 hive_conf_dir="/etc/hive/conf"
 role="$(/usr/share/google/get_metadata_value attributes/dataproc-role)"
 
+# Let spark continue using the existing hive configuration, as it will
+# not want to use hive on tez.
+cp /etc/hive/conf/* /etc/spark/conf/
+# Remove lines containing /etc/hive/conf from spark-env.sh
+sudo sed -i '/\/etc\/hive\/conf/d' /etc/spark/conf/spark-env.sh
```
Comment (pmkc) [inline tez/tez.sh]: '#CLASSPATH=.*/etc/hive/conf#d'
