### PR TITLE
Kafka: wait for ZooKeeper to be up before starting Kafka server

### LINKED ISSUE #487: Kafka initialization fails GCP
The below Kafka initialization return consequently an error:

Schermafbeelding 2019-03-30 om 11 49 50

The tail of the log file looks like this:

Schermafbeelding 2019-03-30 om 11 51 36

I created a cluster from the command line according to:

```
gcloud dataproc clusters create CLUSTER \
		--bucket BUCKET \
		--properties=^#^spark:spark.jars.packages=graphframes:graphframes:0.5.0-spark2.1-s_2.11,com.databricks:spark-xml_2.11:0.4.1 \
		--subnet default \
		--zone europe-west2-b \
		--master-machine-type n1-standard-2 \
		--master-boot-disk-size 50 \
		--num-workers 2 \
		--worker-machine-type n1-standard-2 \
		--worker-boot-disk-size 50 \
		--image-version 1.3-deb9 \
		--project PROJECT_ID \
		--metadata "run-on-master=true" \
		--initialization-actions 'gs://dataproc-initialization-actions/jupyter/jupyter.sh','gs://dataproc-initialization-actions/zookeeper/zookeeper.sh','gs://dataproc-initialization-actions/kafka/kafka.sh','gs://st446-bucket3/my-actions.sh' 
```

### PR DESCRIPTION
**Pull request by functicons**
Fixes #487

### CODE REVIEW

File: kafka/kafka.sh [hunk 1]
```diff
@@ -62,9 +63,24 @@ function get_broker_list() {
       | sed 's/\]/,/'
 }
 
+# Waits for zookeeper to be up or time out.
+function wait_for_zookeeper() {
+  for i in {1..20}; do
+    if "${ZOOKEEPER_HOME}/bin/zkCli.sh" -server "${ZOOKEEPER_ADDRESS}" ls /;
+    then
```
Comment (medb) [inline kafka/kafka.sh]: move then to the same line as `if`
