### PR TITLE
Fix Dr Elephant init action

### LINKED ISSUE #631: dr-elephant is not building
Error:
```
[info] *** 6 TESTS FAILED ***
[error] Failed: Total 492, Failed 8, Errors 0, Passed 483, Skipped 1
[error] Failed tests:
[error] 	com.linkedin.drelephant.tuning.PSOParamGeneratorTest
[error] 	com.linkedin.drelephant.util.SparkUtilsTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 40 s, completed Oct 2, 2019 5:51:13 PM
Build failed...
+ unzip /root/dr-elephant/dist/dr-elephant-2.1.7.zip -d /root/dr-elephant/dist/
unzip:  cannot find or open /root/dr-elephant/dist/dr-elephant-2.1.7.zip, /root/dr-elephant/dist/dr-elephant-2.1.7.zip.zip or /root/dr-elephant/dist/dr-elephant-2.1.7.zip.ZIP.
+ err 'Build step failed'
++ date +%Y-%m-%dT%H:%M:%S%z
+ echo '[2019-10-02T17:51:13+0000]: Build step failed'
[2019-10-02T17:51:13+0000]: Build step failed
+ return 1
```

### PR DESCRIPTION
**Pull request by medb**
Fixes #631

### CODE REVIEW

File: dr-elephant/dr-elephant.sh [hunk 1]
```diff
@@ -192,24 +186,21 @@ Therefore, fetcher does not use other REST calls, which may have significant mem
...
+  echo "spark.eventLog.compress = true" >>"${SPARK_CONF_DIR}/spark-defaults.conf"
 }
 
-
-function prepare_mysql(){
+function prepare_mysql() {
   systemctl restart mysql
-  mysql -u root -proot-password -e " \
-  CREATE DATABASE drelephant;"
+  mysql -u root -proot-password -e "CREATE DATABASE drelephant;"
```
Comment (ChethanUK) [inline dr-elephant/dr-elephant.sh]: It will be nice to have an option to use Cloud SQL [via Cloud SQL Proxy]

Can we work on that as well, if possible..
